name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build_job:
    runs-on: saas-linux-small-amd64
    container:
      image: eclipse-temurin:21-jdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./mvnw clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar